---
title: "Get random values for discriminator and generator"
output: html_notebook
---

**Objective**
- Reproduce the arrays for the discriminator and generator.

**Motivation**
Since the D and G are tensors of 500 lements, we need a small number to confirm both tensors are the same in Python and R.

**Steps**
1. Tensors for discriminator and generator
2. Confirm `fivenum` is the same for Python and R functions


```{r}
library(rTorch)
```

```{python}
import numpy as np
import time
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable


torch.manual_seed(123)
np.random.seed(seed=123)

# Data params
data_mean = 4
data_stddev = 1.25


def get_distribution_sampler(mu, sigma):
    # Bell curve
    return lambda n: torch.Tensor(np.random.normal(mu, sigma, (1, n)))  # Gaussian

def get_generator_input_sampler():
    return lambda m, n: torch.rand(m, n)   # Uniform-dist data into generator, _NOT_ Gaussian    
    
d_sampler = get_distribution_sampler(data_mean, data_stddev)
d_sampler

gi_sampler = get_generator_input_sampler()
gi_sampler


# parameters
g_input_size = 1      # Random noise dimension coming into generator, per output vector
d_input_size = 500    # Minibatch size - cardinality of distributions
minibatch_size = d_input_size

# real data from distribution
d_real_data = d_sampler(d_input_size)
# d_real_data

# generator input
d_gen_input = gi_sampler(minibatch_size, g_input_size)
# d_gen_input
```

```{python}
d_real_data.shape
```

## Objective: fivenum for two tensors

```{python}
from py_functions import fivenum

fivenum(d_real_data.numpy().flatten())
fivenum(d_gen_input.numpy().flatten())
```

```{r}
# compare to R
fivenum(reticulate::py$d_real_data$numpy())
fivenum(reticulate::py$d_gen_input$numpy())
```


## sandbox


```{python}
from py_functions import fivenum

# type(d_real_data.numpy())
# have to flatten the array otherwise len will be 1
nd_real_data = d_real_data.numpy().flatten() 
ld_real_data = nd_real_data.tolist()
# type(ld_real_data)
fivenum(ld_real_data)
```

```{python}
# flatten the array
len(nd_real_data.flatten())
```


```{python}
from py_functions import fivenum
import numpy as np

np_array = np.array(np.random.random(100))
fivenum(np_array)
```
