---
title: "The training distribution"
output: html_notebook
---


**Recipe**
1. Generate the real data
2. Generate the input data for the generator
3. Plot a histogram for the real data
4. Load previously stored fake data (10 samples) and display histogram
5. Take the mean and standard deviation if the 10 samples.
6. Compare these values against the originally `mean` and `sd` supplied.


```{r}
library(rTorch)

# seeds
torch$manual_seed(123L)
np$random$seed(seed=123L)

# Data params for the training data
data_mean   <- 4
data_stddev <- 1.25

# convert lambda functions
name         <- "Only 4 moments"
preprocess   <- function(data) get_moments(data)
d_input_func <- function(x) 4

get_distribution_sampler <- function(mu, sigma) {
    # Python: torch.Tensor(np.random.normal(mu, sigma, (1, n)))
    # the last member of the normal is the shape vector
    function(n) torch$Tensor(np$random$normal(mu, sigma, c(1L, n)))
}

get_generator_input_sampler <- function() {
    # Python: lambda m, n: torch.rand(m, n) 
    function(m, n) torch$rand(m, n)
}    

get_moments <- function(d) {
    mean <- torch$mean(d)
    diffs <- d - mean
    var <- torch$mean(torch$pow(diffs, 2.0))
    std <- torch$pow(var, 0.5)
    zscores <- diffs / std
    skews <- torch$mean(torch$pow(zscores, 3.0))
    kurtoses <- torch$mean(torch$pow(zscores, 4.0)) - 3.0
    # torch.cat((mean.reshape(1,), std.reshape(1,), skews.reshape(1,), kurtoses.reshape(1,)))
    final <- torch$cat(c(torch$reshape(mean, list(1L)), 
                         torch$reshape(std, list(1L)),
                         torch$reshape(skews, list(1L)), 
                         torch$reshape(kurtoses, list(1L))))
    return(final)    
}

# samplers for discriminator and generator
d_sampler  <- get_distribution_sampler(data_mean, data_stddev)
gi_sampler <- get_generator_input_sampler()


# parameters
g_input_size <- 1L      # Random noise coming into generator, per output vector
d_input_size <- 500L    # Minibatch size - cardinality of distributions
minibatch_size <- d_input_size

# real data from distribution
d_real_data = d_sampler(d_input_size)
d_real_data$shape

# generator input
d_gen_input = gi_sampler(minibatch_size, g_input_size)
d_gen_input$shape
```

```{r}
# flatten the tensor first
# v_ means vector
v_d_real_data <- d_real_data$flatten()$numpy()
v_d_gen_input <- d_gen_input$flatten()$numpy()
fivenum(v_d_real_data)
fivenum(v_d_gen_input)
```

```{r}
save(v_d_real_data, file = "s123-real_data.rda")
write.csv(v_d_real_data, file = "s123-real_data.csv")
```


```{r}
# histogram of the real data (R) distribution
hist(v_d_real_data, breaks = 60)
```

```{r}
library(ggplot2)

df <- data.frame(v_d_real_data)
ggplot(df, aes(x=v_d_real_data)) +
    geom_histogram(color="black", fill="white", bins = 50)

```


```{r}
library(ggplot2)
df <- data.frame(v_d_real_data)
ggplot(df, aes(x=v_d_real_data)) +
    geom_histogram(aes(y = ..density..), bins = 50) +
    geom_density(alpha = 0.2, fill = "#CA5521")

```


## Load stored dataset

```{r}
# load ten samples at the highest epoch number
load(file = "s123e5000.rda")
t(sapply(sample, fivenum))
```

```{r}
# Calculate the mean and sd for the 10 fake samples
message("Mean")
sapply(sample, mean)
message("Standard Deviation")
sapply(sample, sd)
```


```{r}
lapply(sample, hist, breaks = 60)
```

```{r}
library(ggplot2)

gghist <- function(x) {
    df <- data.frame(x)  
    ggplot(df, aes(x=x)) +
    geom_histogram(aes(y = ..density..), bins = 50, fill = "white", color = "black") +
    geom_density(alpha = 0.2, fill = "#CA5521")
}

lapply(sample, gghist)
```


```{r}
# generator input
hist(v_d_gen_input)
```

```{r}
# preprocess
preprocess(d_real_data)
```

```{r}

```


```{r}
d_real_data
```

