---
title: "Load data file, convert to dataframe and plot"
output: html_notebook
---

```{r}
load(file = "s123_e5000_synth_metrics.rda")
# save(synth_data, metrics, file = "s123_e500_synth_metrics.rda")
```


```{r}
# convert metrics list of dataframes to one unique dataframe
convert_metrics_to_df <- function(m) {
    get_epoch <- function(x) {
        # extract key values from the list and return as dataframe
        data.frame(run = x$i, epoch = x$epoch, synth_mean = x$mean_fake, 
                   synth_sd = x$sd_fake) 
    }
    do.call(rbind, lapply(metrics, get_epoch)) # mean and standard deviation table
}

metrics_df <- convert_metrics_to_df(metrics)

# convert synthetic dataframes to unique dataframe
convert_synthetic_to_df <- function(synth) {
    # dataframe for all the sythetic datasets
    do.call(rbind, synth)
}

synthetic_df <- convert_synthetic_to_df(synth_data)
```



```{r fig.height=4.5, fig.width=9}
# facet plot of the mean per sample
library(dplyr)
library(ggplot2)

ggplot(metrics_df, aes(x = epoch, y = synth_mean)) +
    geom_point(alpha = 0.3, size = 0.01, color = "darkgreen") +
    geom_hline(aes(yintercept = 4), linetype = "dotted") + 
    scale_y_continuous(name="Mean", breaks = c(0, 2, 4, 6, 8, 10, 12)) +
    scale_x_continuous(name="epoch", limits = c(0, 6000)) +
    facet_wrap(. ~ run, nrow = 2) +
    labs(title = "Mean")
```

```{r fig.height=4.5, fig.width=9}
# facet plot of the standard deviation per sample
library(dplyr)
library(ggplot2)

ggplot(metrics_df, aes(x = epoch, y = synth_sd)) +
    geom_point(alpha = 0.3, size = 0.01, color = "blue") +
    geom_hline(aes(yintercept = 1), linetype = "dotted") + 
    scale_y_continuous(name="SD", breaks = c(0, 1, 2, 3, 4, 5)) +
    scale_x_continuous(name="epoch", limits = c(0, 6000)) +
    facet_wrap(. ~ run, nrow = 2) +
    labs(title = "Standard Deviation")
```

## Synthetic Data

```{r}
# facets for all synthetic datasets
ggplot(synthetic_df, aes(x = data)) +
    geom_histogram(bins = 50) +
    facet_wrap(. ~ run, nrow=2)
```

```{r}
ggplot(synthetic_df, aes(x = run, y = data, group = run)) +
    geom_boxplot() +
    scale_x_discrete(name = "Sample #", limits = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
    
```

```{r}
ggplot(synthetic_df, aes(x = run, y = data, group = run)) +
    geom_boxplot() +
    geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.25) + 
    scale_x_discrete(name = "Sample #", limits = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ))
    
```

```{r}
library(dplyr)
# load the real data
real_data <- read.csv(file = "s123-real_data.csv")
real_data
# add run number 0 for the rel dataset and rename column
real_data_df <- 
real_data %>% 
    mutate(run = 0, data = x, class = "real") %>% 
    select(run, data, class) %>% 
    print
# add column to indicate it is synthetic data
synthetic_df$class <- "synth"
# combine real and synthetic data
real_plus_synth <- rbind(synthetic_df, real_data_df)
real_plus_synth
# plot real and synthetic data
ggplot(real_plus_synth, aes(x = run, y = data, group = run, color = class)) +
    geom_boxplot() +
    geom_jitter(shape = 10, position = position_jitter(0.2), alpha = 0.20) +
    scale_x_discrete(name = "Sample #", limits = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
```

```{r}
# run the mean and standard deviation on the synthetic data samples
library(dplyr)

synthetic_df %>% 
    group_by(run) %>% 
    summarise(mean(data), sd(data))
```

